# .github/workflows/ci.yml
name: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: true  # Ensure submodules are checked out

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential

    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Run main program
      run: |
        cd build
        ./bin/cpp_ci_example

    - name: Run unit tests
      run: |
        cd build
        ctest --output-on-failure
